version: '2.1'

networks:
  servers:

services:
  database:
    build: .
    command: "db"
    networks:
      - servers
    ports:
      - "9000:9000"

  balancer:
    build: .
    command: "lb"
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - servers
    ports:
      - "8090:8090"

  server1:
    build: .
    networks:
      - servers
    depends_on:
      - database
    ports:
      - "8080:8080"

  server2:
    build: .
    networks:
      - servers
    depends_on:
      - database
    ports:
      - "8081:8080"

  server3:
    build: .
    networks:
      - servers
    depends_on:
      - database
    ports:
      - "8082:8080"

